version: '3'

services:
    db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: postgres

    backend: 
        image: backend
        ports:
            - 8080:8080
        environment: 
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - REQUEST_ORIGIN=http://localhost

        depends_on:
            - db

    frontend:
        image: frontend
        ports:
            - 5000:5000

    redis:
        image: redis

    proxy:
        image: nginx:1.19-alpine
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - frontend
            - backend