version: '3'

services:


    db:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db
        volumes:
            - ./database:/var/lib/postgresql/data

    backend: 
        image: backend
        ports:
            - 8080:8080
        environment: 
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=db
            - REQUEST_ORIGIN=http://localhost

        depends_on:
            - db
            - redis

    frontend:
        image: frontend
        ports:
            - 5000:5000
        environment: 
            - API_URL=http://localhost/api

    redis:
        image: redis

    proxy:
        image: nginx:1.19-alpine
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - frontend
            - backend
